In [0]:
!pip install tensorflow==2.0

In [0]:
!pip install mitdeeplearning
import mitdeeplearning as mdl

import numpy as np
import matplotlib.pyplot as plt

In [5]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [0]:
sport=tf.constant('Cricket',tf.string)

In [0]:
Number=tf.constant(65,tf.int64)

In [8]:
print('The dimensions of the tensor {} is {}'.format(sport,tf.rank(sport)))

The dimensions of the tensor b'Cricket' is 0


In [10]:
tf.rank(Number).numpy()

0

In [0]:
List=tf.constant(['Elon Musk','Bill Gates','Richard Branson'])

In [15]:
print(List.numpy())

[b'Elon Musk' b'Bill Gates' b'Richard Branson']


In [16]:
print(tf.rank(List).numpy())

1


In [17]:
print(tf.shape(sport))

tf.Tensor([], shape=(0,), dtype=int32)


In [18]:
print(tf.shape(List))

tf.Tensor([3], shape=(1,), dtype=int32)


In [0]:
import numpy as np


In [0]:
a=np.array([[1,2,3],[4,5,6]])

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a.shape

(2, 3)

In [0]:
#4-d Tensor
A=np.zeros(shape=(10,256,256,3))

In [0]:
A

In [26]:
A.shape

(10, 256, 256, 3)

In [27]:
A.ndim

4

In [0]:
image=tf.constant(A)

In [0]:
image

In [30]:
a[0]

array([1, 2, 3])

In [31]:
a[1]

array([4, 5, 6])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
print('Row Vector:',a[0])
print('Coloumn Vector:',a[:,0])

Row Vector: [1 2 3]
Coloumn Vector: [1 4]


In [0]:
a=tf.constant(12.2)
b=tf.constant(32.1)
c=tf.add(a,b)

In [41]:
c.numpy()

44.3

In [0]:
#Sequential Model In Tensorflow

model=tf.keras.models.Sequential([
                                  tf.keras.layers.Dense(3,kernel_initializer='random_uniform',bias_initializer='zeros')
])

In [0]:
x=tf.constant([[1,2.]],shape=(1,2))

In [47]:
x.numpy()

array([[1., 2.]], dtype=float32)

In [48]:
model.predict(x)

array([[-0.01734922,  0.0557403 ,  0.07605726]], dtype=float32)

In [0]:
#Automatic Gradient Computation In Tensorflow Using tf.Gradienttape()

x=tf.Variable(3.0)


In [0]:
with tf.GradientTape() as tape:
  y=x*x
  

In [51]:
dy_dx=tape(y,x)

TypeError: ignored

In [0]:
#y=3x2

x=tf.Variable(3.0)

with tf.GradientTape() as tape:
  y=3*x*x

In [0]:
dx_dy=tape.gradient(y,x)

In [54]:
print(dx_dy)

tf.Tensor(18.0, shape=(), dtype=float32)


In [56]:
for i in range(2):
  with tf.GradientTape() as tape:
    y=3*x*x*x
  

  grad=tape.gradient(y,x)
  print(grad.numpy())

81.0
81.0
